### ISSUE TITLE
.gitignore の設定追記

### ISSUE THREAD

**Issue by tkamizuka** [JASMINE-Mission/telescope_baseline#18]
https://github.com/JASMINE-Mission/telescope_baseline/blob/f2e5052d2d9347c62c7694273c45e3923f2e932f/.gitignore#L1

こちらですが、下記も追記してよろしいでしょうか。
build/
dist/
*.egg-info/

**Comment by xr0038** [comment]
:+1:

**Comment by tkamizuka** [comment]
軽微なので直接編集します。
